version: '3.4'

services:

    messageBrokerService:
      image: rabbitmq:3-management
      container_name: "RabbitMqMessageBroker"
      ports:
        - 5672:5672
        - 15672:15672
      networks:
        - main

    mapentitiesservice:
        image: ${DOCKER_REGISTRY-}mapentitiesservice
        build:
            context: .
            dockerfile: MapEntitiesService/Dockerfile
        ports:
            - 50001:80
        depends_on:
            - messageBrokerService
        networks:
            - main
        restart: unless-stopped

    seqLoggerService:
        image: datalust/seq:latest
        container_name: "SeqLogger"
        environment:
            - ACCEPT_EULA=Y
        ports:
            - 50002:80
            - 5341:5341
        volumes:
            - c:\Docker\Data\Seq:/data 
        networks:
            - main   

    notificationservice:
        image: ${DOCKER_REGISTRY-}notificationservice
        build:
          context: .
          dockerfile: NotificationService/Dockerfile
        networks:
           - main
        ports:
           - 50003:80

networks:
  main:
    name: mapeenetwork
    
